In [3]:
import os
import json
from pprint import pprint
from collections import Counter
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import math
import pandas as pd
import statsmodels.api as sm
import numpy as np
import datetime as dt


#Put all movie data into a list of dictionaries
def movie_data(movie_file):
    movie_info_path = os.path.join('../data', movie_file)
    json_movie_list = os.listdir(movie_info_path)
    python_movie_list = []
    for json_movie in json_movie_list:
        json_path = os.path.join(movie_info_path, json_movie)
        with open(json_path, 'r') as file:
            python_movie = json.load(file)
            python_movie_list.append(python_movie)
    return python_movie_list

mojo = movie_data('boxofficemojo')
metacritic = movie_data('metacritic')

metacritic_clean = [item for item in metacritic if isinstance(item, dict)]

mojo_df = pd.DataFrame(mojo)
metacritic_df = pd.DataFrame(metacritic_clean)

merged_data = pd.merge(left=mojo_df, right=metacritic_df, how='inner', on=['title'])

def consolodate_director(col_x, col_y):
    director = []
    for i in xrange(len(col_x)):
        if col_x[i] == None:
            director.append(col_y[i])
        if col_y[i] == None:
            director.append(col_x[i])
        director.append(col_x[i])
    return pd.Series(director)

def review_breakdown(review_col, index):
    lst = []
    for group in review_col:
        lst.append(group[index])
    return pd.Series(lst)

def season_by_month(month):
    if month in (12,1,2):
      return 'winter'
    elif month in (3,4,5):
      return 'spring'
    elif month in (6,7,8):
      return 'summer'
    elif month in (9,10,11):
      return 'fall'

def group_ratings(rating):
    if rating not in ('R','PG','PG-13','Not Rated'):
        return 'other'
    else:
        return rating

merged_data['director'] = consolodate_director(merged_data['director_x'], merged_data['director_y'])
merged_data['rating_categories'] = merged_data['rating'].apply(group_ratings)
merged_data['pos_user_reviews'] = review_breakdown(merged_data['num_user_reviews'], 0)
merged_data['nut_user_reviews'] = review_breakdown(merged_data['num_user_reviews'], 1)
merged_data['neg_user_reviews'] = review_breakdown(merged_data['num_user_reviews'], 2)
merged_data['tot_user_reviews'] = review_breakdown(merged_data['num_user_reviews'], 3)
merged_data['pos_critic_reviews'] = review_breakdown(merged_data['num_critic_reviews'], 0)
merged_data['nut_critic_reviews'] = review_breakdown(merged_data['num_critic_reviews'], 1)
merged_data['neg_critic_reviews'] = review_breakdown(merged_data['num_critic_reviews'], 2)
merged_data['tot_critic_reviews'] = review_breakdown(merged_data['num_critic_reviews'], 3)

merged_data.rename(columns={'year_x':'year'}, inplace=True)

del merged_data['year_y']
del merged_data['director_x']
del merged_data['director_y']

merged_data_dropna = merged_data[['production_budget','opening_weekend_take','domestic_gross',
                                  'release_date_wide','widest_release','worldwide_gross','year', 'runtime_minutes',
                                  'metascore','user_score','pos_user_reviews','nut_user_reviews','neg_user_reviews',
                                  'tot_user_reviews','pos_critic_reviews','nut_critic_reviews','neg_critic_reviews',
                                  'tot_critic_reviews','rating','rating_categories']].dropna()

merged_data_dropna['release_month'] = merged_data_dropna['release_date_wide'].apply(lambda x: x[5:7]).astype(int)
merged_data_dropna['season'] = merged_data_dropna['release_month'].apply(season_by_month)

In [4]:
import holidays
from collections import Counter
import datetime

In [5]:
def gen_holiday(end_yr):
    us_hol = []
    for yr in range(1900,end_yr):
        for date in sorted(holidays.US(years=yr).items()):
            us_hol.append(date[0])
    return us_hol

In [6]:
us_holidays = gen_holiday(2015)

In [7]:
def make_date(dt_str):
    if dt_str == None:
        dt_conv = datetime.date(2014,1,3)
    else:
        dt_conv = datetime.date(int(dt_str[0:4]),int(dt_str[5:7]),int(dt_str[8:10]))
    return dt_conv

In [8]:
def hol_weekend(release_date):
    if make_date(release_date) in us_holidays:
        return 1
    elif make_date(release_date) + datetime.timedelta(days=1) in us_holidays:
        return 1
    elif make_date(release_date) + datetime.timedelta(days=2) in us_holidays:
        return 1
    elif make_date(release_date) + datetime.timedelta(days=3) in us_holidays:
        return 1
    elif make_date(release_date) + datetime.timedelta(days=4) in us_holidays:
        return 1
    elif make_date(release_date) + datetime.timedelta(days=5) in us_holidays:
        return 1
    else:
        return 0

In [9]:
# M == 0
def day_of_week(release_date):
    dt_conv = make_date(release_date)
    return dt_conv.weekday()

In [10]:
merged_data['holiday_weekend'] = merged_data['release_date_wide'].apply(hol_weekend)

In [11]:
merged_data['day_of_week'] = merged_data['release_date_wide'].apply(day_of_week)

In [12]:
merged_data['release_date_wide_dt']= merged_data['release_date_wide'].apply(make_date)

In [91]:
def mv_comp(dt):
    df = pd.DataFrame(((merged_data['release_date_wide_dt'] <= make_date(dt)) & ((merged_data['release_date_wide_dt'] + datetime.timedelta(days=14)) >= make_date(dt))))
    comp = df['release_date_wide_dt'].value_counts()
    if comp.empty == True:
        return 0
    else:
        return comp[1]

In [92]:
def mv_comp_take(dt):
    df = pd.DataFrame(((merged_data['release_date_wide_dt'] <= make_date(dt)) & ((merged_data['release_date_wide_dt'] + datetime.timedelta(days=14)) >= make_date(dt))))
    comp = df['release_date_wide_dt'].value_counts()
    if comp.empty == True:
        return 0
    else:
        return comp[1]

9

In [107]:
df = pd.DataFrame(((merged_data['release_date_wide_dt'] <= make_date(dt)) & ((merged_data['release_date_wide_dt'] + datetime.timedelta(days=14)) >= make_date(dt))))
df = df.rename(columns ={'release_date_wide_dt':'competitors'})
df2 = pd.concat([df,merged_data],axis =1)
df2
#df3 = df2.groupby('competitors')

,competitors,alt_title,domestic_gross,mojo_slug,opening_per_theater,opening_weekend_take,production_budget,release_date_limited,release_date_wide,title,...,neg_user_reviews,tot_user_reviews,pos_critic_reviews,nut_critic_reviews,neg_critic_reviews,tot_critic_reviews,holiday_weekend,day_of_week,release_date_wide_dt,competitors
0,False,10 Things I Hate About You (1999),38178166.0,10thingsihateaboutyou,3668.0,8330681.0,30000000.0,None,1999-03-31,10 Things I Hate About You,...,1,29,18,7,1,26,0,2,1999-03-31,2
1,False,10 Years (2012),203373.0,10years,7569.0,22707.0,NaN,None,2012-09-14,10 Years,...,1,6,7,11,0,18,0,4,2012-09-14,11
2,False,The 11th Hour (2007),707343.0,11thhour,15213.0,60853.0,NaN,None,2007-08-17,The 11th Hour,...,5,12,20,9,1,30,0,4,2007-08-17,11
3,False,127 Hours (2010),18335230.0,127hours,2333.0,2136801.0,18000000.0,2010-11-05,2011-01-28,127 Hours,...,16,118,37,1,0,38,0,4,2011-01-28,14
4,False,12 Rounds (2009),12234694.0,12rounds,2286.0,5329240.0,NaN,None,2009-03-27,12 Rounds,...,12,20,1,5,7,13,0,4,2009-03-27,10
5,False,13 Going on 30 (2004),57231747.0,13goingon30,6123.0,21054283.0,37000000.0,None,2004-04-23,13 Going on 30,...,4,33,20,15,0,35,0,4,2004-04-23,8
6,False,13 Sins (2014),13809.0,13sins,206.0,9261.0,NaN,None,2014-04-18,13 Sins,...,2,11,1,9,1,11,0,4,2014-04-18,17
7,False,13 Tzameti (2006),121390.0,13tzameti,10805.0,10805.0,NaN,None,2006-07-28,13 Tzameti,...,1,7,16,7,2,25,0,4,2006-07-28,11
8,False,1408 (2007),71985628.0,1408,7698.0,20617667.0,25000000.0,None,2007-06-22,1408,...,20,80,20,7,0,27,0,4,2007-06-22,5
9,False,16 Blocks (2006),36895141.0,16blocks,4381.0,11855260.0,NaN,None,2006-03-03,16 Blocks,...,8,47,24,8,2,34,0,4,2006-03-03,9
10,False,17 Again (2009),64167069.0,17again,7288.0,23722310.0,NaN,None,2009-04-17,17 Again,...,8,43,9,13,5,27,0,4,2009-04-17,5
11,False,2012 (2009),166112167.0,2012,19165.0,65237614.0,200000000.0,None,2009-11-13,2012,...,82,233,14,14,6,34,0,4,2009-11-13,5
12,False,2046 (2005),1444588.0,2046,28268.0,113074.0,12000000.0,None,2005-08-05,2046,...,9,33,27,7,0,34,0,4,2005-08-05,10
13,False,20 Feet from Stardom (2013),4946445.0,20feetfromstardom,18199.0,54596.0,NaN,None,2013-06-14,20 Feet from Stardom,...,0,7,25,0,0,25,0,4,2013-06-14,14
14,False,21 (2008),81159365.0,21,9103.0,24105943.0,35000000.0,None,2008-03-28,21,...,12,51,6,21,2,29,0,4,2008-03-28,8
15,False,21 and Over (2013),25682380.0,21andover,3159.0,8754168.0,13000000.0,None,2013-03-01,21 and Over,...,8,27,3,8,10,21,0,4,2013-03-01,9
16,False,21 Grams (2003),16290476.0,21grams,34306.0,274454.0,20000000.0,None,2003-11-21,21 Grams,...,9,60,31,5,5,41,0,4,2003-11-21,5
17,False,21 Jump Street (2012),138447667.0,21jumpstreet,11632.0,36302612.0,42000000.0,None,2012-03-16,21 Jump Street,...,20,173,32,9,0,41,0,4,2012-03-16,12
18,False,25th Hour (2002),13084595.0,25thhour,21773.0,108865.0,5000000.0,None,2002-12-19,25th Hour,...,9,50,24,10,3,37,0,3,2002-12-19,6
19,False,27 Dresses (2008),76808654.0,27dresses,7526.0,23007725.0,30000000.0,None,2008-01-18,27 Dresses,...,9,40,7,22,2,31,1,4,2008-01-18,10
20,False,28 Days (2000),37170488.0,28days,4086.0,10310672.0,43000000.0,None,2000-04-14,28 Days,...,1,8,9,10,7,26,0,4,2000-04-14,3
21,False,28 Weeks Later (2007),28638916.0,28weekslater,4258.0,9807292.0,NaN,None,2007-05-11,28 Weeks Later,...,36,181,31,3,0,34,0,4,2007-05-11,7
22,False,2 Days in New York (2012),633210.0,2daysinnewyork,11971.0,23942.0,NaN,None,2012-08-10,2 Days in New York,...,2,7,17,8,1,26,0,4,2012-08-10,8
23,False,2 Days in Paris (2007),4433994.0,2daysinparis,17364.0,173641.0,NaN,None,2007-08-10,2 Days in Paris,...,8,28,27,3,0,30,0,4,2007-08-10,10
24,False,2 Fast 2 Furious (2003),127154901.0,2fast2furious,14810.0,50472480.0,76000000.0,None,2003-06-06,2 Fast 2 Furious,...,35,106,7,14,14,35,0,4,2003-06-06,6
25,False,2 Guns (2013),75612460.0,2guns,8945.0,27059130.0,61000000.0,None,2013-08-02,2 Guns,...,6,51,19,21,3,43,0,4,2013-08-02,14
26,False,300 (2007),210614939.0,300,22844.0,70885301.0,65000000.0,None,2007-03-09,300,...,101,524,16,13,6,35,0,4,2007-03-09,8
27,False,3000 Miles to Graceland (2001),15749959.0,3000milestograceland,2813.0,7160521.0,62000000.0,None,2001-02-23,3000 Miles to Graceland,...,11,37,3,7,20,30,0,4,2001-02-23,2
28,False,30 Beats (2012),14693.0,30beats,575.0,8624.0,NaN,None,2012-07-20,30 Beats,...,1,1,0,2,10,12,0,4,2012-07-20,3
29,False,30 Days of Night (2007),39568996.0,30daysofnight,5587.0,15951902.0,30000000.0,None,2007-10-19,30 Days of Night,...,17,77,16,9,4,29,0,4,2007-10-19,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2404,False,Wrong Turn (2003),15418790.0,wrongturn,3195.0,5161498.0,12600000.0,None,2003-05-30,Wrong Turn,...,13,39,2,7,8,17,0,4,2003-05-30,4
2405,False,Wyatt Earp (1994),25052000.0,wyattearp,4057.0,7543504.0,63000000.0,None,1994-06-24,Wyatt Earp,...,0,3,4,12,4,20,0,4,1994-06-24,3
2406,False,Xanadu (1980),22762571.0,xanadu,5910.0,1471595.0,NaN,None,1980-08-08,Xanadu,...,0,1,3,3,3,9,0,4,1980-08-08,1
2407,False,XXY (2008),48334.0,xxy,3241.0,3241.0,NaN,None,2008-05-02,XXY,...,0,4,12,2,1,15,0,4,2008-05-02,9
2408,False,The Year My Parents Went on Vacation (2008),807117.0,yearmyparentswentonvacation,4481.0,80655.0,NaN,None,2008-02-15,The Year My Parents Went on Vacation,...,1,6,16,3,0,19,1,4,2008-02-15,11
2409,False,Year One (2009),43337279.0,yearone,6489.0,19610304.0,60000000.0,None,2009-06-19,Year One,...,28,71,6,8,14,28,0,4,2009-06-19,9
2410,False,Yes Man (2008),97690976.0,yesman,5318.0,18262471.0,70000000.0,None,2008-12-19,Yes Man,...,10,58,8,18,4,30,0,4,2008-12-19,9
2411,False,Yogi Bear (2010),100246011.0,yogibear,4669.0,16411322.0,80000000.0,None,2010-12-17,Yogi Bear,...,14,32,2,10,11,23,0,4,2010-12-17,8
2412,False,You Again (2010),25702053.0,youagain,3300.0,8407513.0,20000000.0,None,2010-09-24,You Again,...,8,24,1,10,14,25,0,4,2010-09-24,15
2413,False,You Don't Mess with the Zohan (2008),100018837.0,youdontmesswiththezohan,11130.0,38531374.0,90000000.0,None,2008-06-06,You Don't Mess with the Zohan,...,38,93,14,17,6,37,0,4,2008-06-06,8
2414,False,You Got Served (2004),40363810.0,yougotserved,8340.0,16123105.0,8000000.0,None,2004-01-30,You Got Served,...,13,48,1,15,8,24,0,4,2004-01-30,8
2415,False,You Kill Me (2007),2429367.0,youkillme,6677.0,233709.0,NaN,None,2007-06-22,You Kill Me,...,0,10,20,3,2,25,0,4,2007-06-22,5
2416,False,"You, Me and Dupree (2006)",75628110.0,youmeanddupree,6874.0,21525560.0,54000000.0,None,2006-07-14,"You, Me and Dupree",...,8,28,9,14,6,29,0,4,2006-07-14,5
2417,False,Young Adult (2011),16311571.0,youngadult,3451.0,3403159.0,12000000.0,2011-12-09,2011-12-16,Young Adult,...,13,60,35,6,1,42,0,4,2011-12-16,6
2418,False,The Young Victoria (2009),11001272.0,youngvictoria,5923.0,260591.0,35000000.0,None,2009-12-18,The Young Victoria,...,0,15,21,7,1,29,0,4,2009-12-18,7
2419,False,You're Next (2013),18494006.0,yourenext,2881.0,7020196.0,NaN,None,2013-08-23,You're Next,...,12,63,24,5,3,32,0,4,2013-08-23,18
2420,False,Your Highness (2011),21596445.0,yourhighness,3380.0,9360020.0,49900000.0,None,2011-04-08,Your Highness,...,22,61,2,14,17,33,0,4,2011-04-08,16
2421,False,Your Sister's Sister (2012),1636190.0,yoursisterssister,8402.0,109221.0,NaN,None,2012-06-15,Your Sister's Sister,...,6,14,24,5,0,29,0,4,2012-06-15,14
2422,False,"Yours, Mine and Ours (2005)",53412862.0,yoursmineandours,5446.0,17461108.0,45000000.0,None,2005-11-23,"Yours, Mine and Ours",...,11,18,1,12,12,25,1,2,2005-11-23,9
2423,False,Youth in Revolt (2010),15281286.0,youthinrevolt,3678.0,6888334.0,18000000.0,None,2010-01-08,Youth in Revolt,...,3,23,25,10,0,35,0,4,2010-01-08,9
2424,False,You've Been Trumped (2012),29273.0,youvebeentrumped,4497.0,4497.0,NaN,None,2012-08-03,You've Been Trumped,...,1,2,4,7,1,12,0,4,2012-08-03,10
2425,False,You've Got Mail (1998),115821495.0,youvegotmail,6847.0,18426749.0,65000000.0,None,1998-12-18,You've Got Mail,...,3,6,13,4,2,19,0,4,1998-12-18,2
2426,False,You Will Be My Son (2013),285151.0,youwillbemyson,15301.0,15301.0,NaN,None,2013-08-16,You Will Be My Son,...,0,1,12,6,0,18,0,4,2013-08-16,17
2427,False,Yves Saint Laurent (2014),723593.0,yvessaintlaurent,12104.0,24207.0,NaN,None,2014-06-25,Yves Saint Laurent,...,0,2,9,14,2,25,0,2,2014-06-25,10
2428,False,Zack and Miri Make a Porno (2008),31457946.0,zackandmirimakeaporno,3680.0,10065630.0,24000000.0,None,2008-10-31,Zack and Miri Make a Porno,...,14,62,15,16,2,33,0,4,2008-10-31,6
2429,False,Zaytoun (2013),42330.0,zaytoun,2050.0,4100.0,NaN,None,2013-09-20,Zaytoun,...,0,1,3,8,4,15,0,4,2013-09-20,18
2430,False,The Zero Theorem (2014),257706.0,zerotheorem,1330.0,83803.0,NaN,None,2014-09-19,The Zero Theorem,...,0,8,8,15,5,28,0,4,2014-09-19,17
2431,False,Zombieland (2009),75590286.0,zombieland,8147.0,24733155.0,23600000.0,None,2009-10-02,Zombieland,...,23,212,25,6,0,31,0,4,2009-10-02,12
2432,False,Zookeeper (2011),80360843.0,zookeeper,5763.0,20065617.0,80000000.0,None,2011-07-08,Zookeeper,...,20,33,4,10,15,29,0,4,2011-07-08,13
2433,False,Zoom (2006),11989328.0,zoom,1803.0,4510408.0,NaN,None,2006-08-11,Zoom,...,8,15,0,3,11,14,0,4,2006-08-11,12

In [94]:
merged_data['competitors'] = merged_data['release_date_wide'].apply(mv_comp)

In [95]:
merged_data.sort('release_date_wide_dt')

c:\Users\rgt709\AppData\Local\Continuum\Anaconda\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

,alt_title,domestic_gross,mojo_slug,opening_per_theater,opening_weekend_take,production_budget,release_date_limited,release_date_wide,title,widest_release,...,neg_user_reviews,tot_user_reviews,pos_critic_reviews,nut_critic_reviews,neg_critic_reviews,tot_critic_reviews,holiday_weekend,day_of_week,release_date_wide_dt,competitors
1716,Pinocchio (1940),84254167.0,pinocchio,NaN,NaN,NaN,None,1940-02-09,Pinocchio,NaN,...,17,25,0,2,13,15,0,4,1940-02-09,1
2024,Somebody Up There Likes Me (1956),NaN,somebodyuptherelikesme,NaN,NaN,NaN,None,1956-07-03,Somebody Up There Likes Me,NaN,...,0,1,7,3,2,12,1,1,1956-07-03,1
2136,The Ten Commandments (1956),65500000.0,tencommandments,NaN,NaN,NaN,None,1956-10-05,The Ten Commandments,NaN,...,2,3,1,2,3,6,0,4,1956-10-05,1
2002,Sleeping Beauty (1959),51600000.0,sleepingbeauty,NaN,NaN,NaN,None,1959-01-29,Sleeping Beauty,NaN,...,3,9,10,8,2,20,0,3,1959-01-29,1
1768,Psycho (1960),32000000.0,psycho,NaN,NaN,806947.0,None,1960-06-16,Psycho,NaN,...,8,12,8,11,4,23,0,3,1960-06-16,1
951,The Graduate (1967),104945305.0,graduate,NaN,NaN,NaN,None,1967-12-21,The Graduate,NaN,...,1,18,7,3,0,10,1,3,1967-12-21,1
713,Easy Rider (1969),NaN,easyrider,NaN,NaN,360000.0,None,1969-07-14,Easy Rider,NaN,...,3,8,7,0,0,7,0,0,1969-07-14,1
401,Butch Cassidy and the Sundance Kid (1969),102308889.0,butchcassidyandthesundancekid,NaN,NaN,NaN,None,1969-09-23,Butch Cassidy and the Sundance Kid,NaN,...,0,13,6,0,2,8,0,1,1969-09-23,1
1685,Patton (1970),61749765.0,patton,NaN,NaN,12000000.0,None,1970-02-04,Patton,NaN,...,1,10,9,0,0,9,0,2,1970-02-04,1
1384,Love Story (1970),106397186.0,lovestory,NaN,NaN,NaN,None,1970-12-16,Love Story,NaN,...,1,2,4,1,0,5,0,2,1970-12-16,1
918,The Godfather (1972),134966411.0,godfather,50398.0,302393.0,6000000.0,None,1972-03-15,The Godfather,NaN,...,25,375,14,0,0,14,0,2,1972-03-15,1
471,Chinatown (1974),29200000.0,chinatown,NaN,NaN,NaN,None,1974-06-21,Chinatown,NaN,...,0,28,10,0,0,10,0,4,1974-06-21,1
1203,Jaws (1975),260000000.0,jaws,9111.0,6150000.0,7000000.0,1975-06-20,1975-07-25,Jaws,675.0,...,9,77,8,1,0,9,0,4,1975-07-25,1
1861,The Rocky Horror Picture Show (1975),112892319.0,rockyhorrorpictureshow,NaN,NaN,NaN,None,1975-09-26,The Rocky Horror Picture Show,NaN,...,2,19,5,1,1,7,0,4,1975-09-26,1
958,Grease (1978),188755690.0,grease,10373.0,8941717.0,6000000.0,None,1978-06-16,Grease,862.0,...,3,19,14,0,1,15,0,4,1978-06-16,1
986,Halloween (1978),47000000.0,halloween,NaN,NaN,325000.0,None,1978-10-25,Halloween,NaN,...,50,152,4,8,6,18,0,2,1978-10-25,2
985,Halloween (1978),47000000.0,halloween,NaN,NaN,325000.0,None,1978-10-25,Halloween,NaN,...,2,64,9,1,0,10,0,2,1978-10-25,2
618,The Deer Hunter (1978),48979328.0,deerhunter,NaN,NaN,15000000.0,None,1978-12-08,The Deer Hunter,NaN,...,4,27,5,2,0,7,0,4,1978-12-08,1
1411,Manhattan (1979),39946780.0,manhattan,16749.0,485734.0,NaN,None,1979-04-25,Manhattan,NaN,...,0,11,8,1,0,9,0,2,1979-04-25,1
118,The Amityville Horror (1979),86432000.0,amityvillehorror,10485.0,7843467.0,NaN,None,1979-07-27,The Amityville Horror,748.0,...,15,56,3,15,13,31,0,4,1979-07-27,1
1967,The Shining (1980),44360123.0,shining,62233.0,622337.0,19000000.0,None,1980-05-23,The Shining,NaN,...,3,61,6,2,2,10,1,4,1980-05-23,1
2406,Xanadu (1980),22762571.0,xanadu,5910.0,1471595.0,NaN,None,1980-08-08,Xanadu,NaN,...,0,1,3,3,3,9,0,4,1980-08-08,1
1632,Ordinary People (1980),54766923.0,ordinarypeople,28389.0,170335.0,NaN,None,1980-09-19,Ordinary People,NaN,...,0,2,10,1,0,11,0,4,1980-09-19,1
2028,Somewhere in Time (1980),9709597.0,somewhereintime,3260.0,1203011.0,NaN,None,1980-10-03,Somewhere in Time,NaN,...,1,4,2,2,3,7,0,4,1980-10-03,2
1792,Raiders of the Lost Ark (1981),248159971.0,raidersofthelostark,7704.0,8305823.0,18000000.0,None,1981-06-12,Raiders of the Lost Ark,1078.0,...,4,81,10,0,1,11,0,4,1981-06-12,1
167,Arthur (1981),95461682.0,arthur,3879.0,2719534.0,NaN,None,1981-07-17,Arthur,701.0,...,10,25,4,21,12,37,0,4,1981-07-17,1
592,Das Boot (1982),11487676.0,dasboot,13497.0,26994.0,NaN,None,1982-02-10,Das Boot,2.0,...,0,14,12,3,0,15,1,2,1982-02-10,1
528,Conan the Barbarian (1982),39565475.0,conanthebarbarian,6883.0,9603139.0,NaN,None,1982-05-14,Conan the Barbarian,1683.0,...,0,16,4,3,3,10,0,4,1982-05-14,2
527,Conan the Barbarian (1982),39565475.0,conanthebarbarian,6883.0,9603139.0,NaN,None,1982-05-14,Conan the Barbarian,1683.0,...,24,68,2,12,15,29,0,4,1982-05-14,2
133,Annie (1982),57059003.0,annie,4820.0,5312062.0,NaN,1982-05-21,1982-06-18,Annie,1102.0,...,15,41,5,19,14,38,0,4,1982-06-18,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1945,Seventh Son (2015),17223265.0,seventhson,2510.0,7217640.0,95000000.0,None,2015-02-06,Seventh Son,2875.0,...,11,24,2,16,14,32,0,4,2015-02-06,14
1234,Jupiter Ascending (2015),47124828.0,jupiterascending,5776.0,18372372.0,176000000.0,None,2015-02-06,Jupiter Ascending,3181.0,...,29,106,8,17,15,40,0,4,2015-02-06,14
648,Digging Up the Marrow (2015),10969.0,diggingupthemarrow,NaN,NaN,NaN,None,2015-02-12,Digging Up the Marrow,1.0,...,0,1,1,6,1,8,0,3,2015-02-12,7
796,Fifty Shades of Grey (2015),165807055.0,fiftyshadesofgrey,23360.0,85171450.0,40000000.0,None,2015-02-13,Fifty Shades of Grey,3655.0,...,82,167,9,29,8,46,0,4,2015-02-13,8
2378,Wild Tales (2015),2216000.0,wildtales,21275.0,85100.0,NaN,None,2015-02-20,Wild Tales,122.0,...,0,14,29,4,0,33,0,4,2015-02-20,8
703,The DUFF (2015),33637582.0,duff,4198.0,10809149.0,8500000.0,None,2015-02-20,The DUFF,2622.0,...,0,13,14,10,4,28,0,4,2015-02-20,8
2069,Still Alice (2015),18451000.0,stillalice,2831.0,2166000.0,5000000.0,2015-01-16,2015-02-20,Still Alice,1318.0,...,2,34,31,9,1,41,0,4,2015-02-20,8
871,Futuro Beach (2015),18626.0,futurobeach,3324.0,3324.0,NaN,None,2015-02-27,Futuro Beach,4.0,...,1,1,5,3,0,8,0,4,2015-02-27,8
1420,Maps to the Stars (2015),350741.0,mapstothestars,2173.0,143422.0,NaN,None,2015-02-27,Maps to the Stars,66.0,...,5,11,25,11,3,39,0,4,2015-02-27,8
43,'71 (2015),1223516.0,71,13940.0,55761.0,NaN,None,2015-02-27,'71,121.0,...,0,11,31,2,0,33,0,4,2015-02-27,8
75,A La Mala (2015),3629842.0,alamala,3651.0,1402118.0,NaN,None,2015-02-27,A La Mala,384.0,...,0,1,0,2,0,2,0,4,2015-02-27,8
446,Chappie (2015),31121710.0,chappie,4170.0,13346782.0,49000000.0,None,2015-03-06,Chappie,3201.0,...,18,118,8,20,11,39,0,4,2015-03-06,8
33,3 Hearts (2015),148162.0,3hearts,11794.0,11794.0,NaN,None,2015-03-13,3 Hearts,29.0,...,1,1,10,9,0,19,0,4,2015-03-13,7
1874,Run All Night (2015),25942324.0,runallnight,3473.0,11012305.0,50000000.0,None,2015-03-13,Run All Night,3171.0,...,1,21,19,13,2,34,0,4,2015-03-13,7
122,Amour Fou (2015),10661.0,amourfou,1462.0,4385.0,NaN,None,2015-03-18,Amour Fou,3.0,...,0,1,11,4,0,15,0,2,2015-03-18,4
1939,Serena (2015),170931.0,serena,1696.0,100090.0,NaN,None,2015-03-27,Serena,59.0,...,4,4,4,13,12,29,0,4,2015-03-27,9
1187,It Follows (2015),11903874.0,itfollows,3129.0,3811052.0,NaN,2015-03-13,2015-03-27,It Follows,1655.0,...,29,67,35,2,0,37,0,4,2015-03-27,9
2359,While We're Young (2015),2355000.0,whilewereyoung,56922.0,227688.0,NaN,None,2015-03-27,While We're Young,246.0,...,2,12,35,7,0,42,0,4,2015-03-27,9
887,Get Hard (2015),71441955.0,gethard,10647.0,33803253.0,40000000.0,None,2015-03-27,Get Hard,3212.0,...,4,18,3,21,19,43,0,4,2015-03-27,9
1892,The Salt of the Earth (2015),137500.0,saltoftheearth,11225.0,44900.0,NaN,None,2015-03-27,The Salt of the Earth,27.0,...,0,1,23,2,0,25,0,4,2015-03-27,9
1849,The Riot Club (2015),3643.0,riotclub,2188.0,2188.0,NaN,None,2015-03-27,The Riot Club,4.0,...,1,2,4,12,2,18,0,4,2015-03-27,9
1283,Lambert & Stamp (2015),33000.0,lambertandstamp,4500.0,13500.0,NaN,None,2015-04-03,Lambert & Stamp,7.0,...,0,1,13,1,1,15,0,4,2015-04-03,8
720,Effie Gray (2015),NaN,effiegray,NaN,NaN,NaN,None,2015-04-03,Effie Gray,NaN,...,0,1,10,17,0,27,0,4,2015-04-03,8
2394,Woman in Gold (2015),9436128.0,womaningold,3646.0,5483125.0,NaN,2015-04-01,2015-04-10,Woman in Gold,1504.0,...,0,9,11,18,2,31,0,4,2015-04-10,15
1367,Lost River (2015),22115.0,lostriver,6943.0,20828.0,NaN,None,2015-04-10,Lost River,3.0,...,0,5,3,13,4,20,0,4,2015-04-10,15
761,Ex Machina (2015),250000.0,exmachina,62500.0,250000.0,NaN,None,2015-04-10,Ex Machina,4.0,...,1,8,23,5,0,28,0,4,2015-04-10,15
1255,Kill Me Three Times (2015),15477.0,killmethreetimes,967.0,15477.0,NaN,None,2015-04-10,Kill Me Three Times,16.0,...,0,1,3,5,12,20,0,4,2015-04-10,15
582,Danny Collins (2015),2503853.0,dannycollins,2002.0,1479158.0,NaN,2015-03-20,2015-04-10,Danny Collins,739.0,...,0,2,16,13,0,29,0,4,2015-04-10,15
499,Clouds of Sils Maria (2015),61810.0,cloudsofsilsmaria,20603.0,61810.0,NaN,None,2015-04-10,Clouds of Sils Maria,3.0,...,0,2,24,2,1,27,0,4,2015-04-10,15
629,Desert Dancer (2015),45585.0,desertdancer,1772.0,40763.0,NaN,None,2015-04-10,Desert Dancer,23.0,...,0,1,4,11,1,16,0,4,2015-04-10,15

In [ ]:
merged_data.loc[lambda df: df.holiday_weekend >= True, :].count()

In [108]:
merged_data_dropna = merged_data[['production_budget','opening_weekend_take','domestic_gross',
                                  'release_date_wide','widest_release','worldwide_gross','year', 'runtime_minutes',
                                  'metascore','user_score','pos_user_reviews','nut_user_reviews','neg_user_reviews',
                                  'tot_user_reviews','pos_critic_reviews','nut_critic_reviews','neg_critic_reviews',
                                  'tot_critic_reviews','rating','rating_categories','holiday_weekend','day_of_week','competitors']].dropna()
merged_data_dropna['release_month'] = merged_data_dropna['release_date_wide'].apply(lambda x: x[5:7]).astype(int)
merged_data_dropna['season'] = merged_data_dropna['release_month'].apply(season_by_month)

In [109]:
merged_data_dropna['widest_release_sq'] = merged_data_dropna['widest_release'].apply(lambda X:np.log(X))
merged_data_dropna['holiday_weekend_sq'] = merged_data_dropna['holiday_weekend'].apply(lambda X:X**3)

In [110]:
msk = np.random.rand(len(merged_data_dropna)) < 0.8
train = merged_data_dropna[msk]
test = merged_data_dropna[~msk]

In [112]:
X = sm.add_constant(train[['production_budget','runtime_minutes','holiday_weekend','day_of_week','competitors',
                                            'widest_release_sq','holiday_weekend_sq','widest_release','metascore']].join(
                                            pd.get_dummies(train['season']).join(
                                            pd.get_dummies(train['rating_categories']))))
Y = train['opening_weekend_take']

linmodel = sm.OLS(Y,X).fit()

linmodel.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results
================================================================================
Dep. Variable:     opening_weekend_take   R-squared:                       0.604
Model:                              OLS   Adj. R-squared:                  0.598
Method:                   Least Squares   F-statistic:                     89.60
Date:                  Fri, 12 Aug 2016   Prob (F-statistic):          2.22e-165
Time:                          10:48:28   Log-Likelihood:                -15836.
No. Observations:                   896   AIC:                         3.170e+04
Df Residuals:                       880   BIC:                         3.178e+04
Df Model:                            15
Covariance Type:              nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [95.0% Conf. Int.]
--------------------------------------------------------------------------------------
const               8.908e+06   4.01e+06      2.223      0.026      1.04e+06  1.68e+07
production_budget      0.1094      0.013      8.455      0.000         0.084     0.135
runtime_minutes    -1.763e+04   2.15e+04     -0.818      0.413     -5.99e+04  2.47e+04
holiday_weekend     1.404e+05   5.44e+05      0.258      0.797     -9.28e+05  1.21e+06
day_of_week         3.535e+05   6.59e+05      0.536      0.592      -9.4e+05  1.65e+06
competitors        -2.287e+05   9.55e+04     -2.395      0.017     -4.16e+05 -4.13e+04
widest_release_sq  -6.084e+06   7.61e+05     -7.992      0.000     -7.58e+06 -4.59e+06
holiday_weekend_sq  1.404e+05   5.44e+05      0.258      0.797     -9.28e+05  1.21e+06
widest_release       1.53e+04    895.490     17.088      0.000      1.35e+04  1.71e+04
metascore           1.818e+05   2.44e+04      7.454      0.000      1.34e+05   2.3e+05
fall                1.069e+06   1.22e+06      0.879      0.380     -1.32e+06  3.45e+06
spring              4.303e+06   1.21e+06      3.564      0.000      1.93e+06  6.67e+06
summer              2.884e+06   1.14e+06      2.539      0.011      6.55e+05  5.11e+06
winter              6.527e+05   1.31e+06      0.497      0.620     -1.93e+06  3.23e+06
Not Rated          -1.091e+06   3.08e+06     -0.355      0.723     -7.13e+06  4.95e+06
PG                 -2.169e+06   1.33e+06     -1.625      0.105     -4.79e+06  4.51e+05
PG-13               3.706e+06   1.27e+06      2.926      0.004      1.22e+06  6.19e+06
R                   3.331e+06   1.23e+06      2.703      0.007      9.13e+05  5.75e+06
other               5.131e+06   1.48e+06      3.460      0.001      2.22e+06  8.04e+06
==============================================================================
Omnibus:                      525.901   Durbin-Watson:                   1.743
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9004.895
Skew:                           2.319   Prob(JB):                         0.00
Kurtosis:                      17.822   Cond. No.                     4.42e+24
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.93e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [113]:
train_pred = pd.DataFrame(linmodel.predict(X),index=train.index)
final = pd.concat([train_pred,Y,X],axis=1)
final

,0,opening_weekend_take,const,production_budget,runtime_minutes,holiday_weekend,day_of_week,competitors,widest_release_sq,holiday_weekend_sq,...,metascore,fall,spring,summer,winter,Not Rated,PG,PG-13,R,other
0,1.970277e+07,8330681.0,1,30000000.0,97.0,0,2,2,7.745436,0,...,70.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,-1.153493e+06,2136801.0,1,18000000.0,94.0,0,4,14,6.820016,0,...,82.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
5,3.245290e+07,21054283.0,1,37000000.0,98.0,0,4,8,8.146999,0,...,57.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,2.198076e+07,20617667.0,1,25000000.0,104.0,0,4,5,7.913155,0,...,64.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
11,4.510126e+07,65237614.0,1,200000000.0,158.0,0,4,5,8.144389,0,...,49.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
12,3.392896e+06,113074.0,1,12000000.0,129.0,0,4,10,4.110874,0,...,78.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
14,2.344416e+07,24105943.0,1,35000000.0,123.0,0,4,8,7.990238,0,...,48.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
15,1.603222e+07,8754168.0,1,13000000.0,93.0,0,4,9,7.926964,0,...,34.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
16,-4.022392e+06,274454.0,1,20000000.0,124.0,0,4,5,6.018593,0,...,70.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
19,2.072071e+07,23007725.0,1,30000000.0,111.0,1,4,10,8.030735,1,...,47.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
20,1.984290e+07,10310672.0,1,43000000.0,103.0,0,4,3,7.833204,0,...,46.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
24,3.167107e+07,50472480.0,1,76000000.0,107.0,0,4,6,8.136811,0,...,38.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
25,2.565067e+07,27059130.0,1,61000000.0,109.0,0,4,14,8.015658,0,...,55.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
26,3.138011e+07,70885301.0,1,65000000.0,117.0,0,4,8,8.095599,0,...,51.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
27,1.347470e+07,7160521.0,1,62000000.0,125.0,0,4,2,7.841886,0,...,21.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
29,1.800176e+07,15951902.0,1,30000000.0,113.0,0,4,13,7.958227,0,...,53.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
30,1.955393e+07,13330118.0,1,28000000.0,83.0,0,4,14,7.968320,0,...,49.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
36,2.746158e+07,9910310.0,1,175000000.0,118.0,1,2,9,7.897296,1,...,28.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
38,3.443161e+07,39852237.0,1,75000000.0,99.0,1,4,5,8.192017,1,...,48.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
40,8.960077e+06,6254.0,1,12000000.0,120.0,0,4,7,1.791759,0,...,31.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
45,2.192447e+07,51240555.0,1,41000000.0,110.0,1,4,6,7.857481,1,...,77.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
46,8.037813e+06,14252888.0,1,40000000.0,123.0,0,4,4,7.770645,0,...,19.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
47,1.068287e+07,10740446.0,1,30000000.0,79.0,0,2,7,7.630461,0,...,60.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
49,-4.000184e+06,62087.0,1,10000000.0,98.0,0,4,11,5.375278,0,...,64.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
51,5.331919e+06,8533162.0,1,30000000.0,125.0,0,4,5,7.122867,0,...,85.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
55,2.019288e+07,10023835.0,1,23000000.0,90.0,0,4,10,7.978311,0,...,47.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
59,-2.325672e+06,1130480.0,1,19000000.0,114.0,1,4,12,6.510258,1,...,83.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
61,2.563970e+07,21157730.0,1,50200000.0,99.0,0,4,11,7.954021,0,...,60.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
62,9.969936e+06,6154984.0,1,13000000.0,107.0,0,4,13,7.678326,0,...,48.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
68,2.216449e+07,14064317.0,1,28000000.0,102.0,0,4,5,8.122371,0,...,41.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2363,2.039034e+07,19676748.0,1,37000000.0,109.0,0,2,6,7.937375,0,...,41.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2364,3.741878e+07,24852258.0,1,150000000.0,131.0,0,4,14,8.077758,0,...,52.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2368,1.386102e+07,4915104.0,1,35000000.0,101.0,0,4,8,7.917536,0,...,28.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2369,-3.618481e+05,59848.0,1,18000000.0,144.0,1,2,8,4.663439,1,...,82.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2370,1.129633e+07,11226239.0,1,70000000.0,104.0,0,4,1,7.376508,0,...,83.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2372,1.107148e+07,9610204.0,1,40000000.0,102.0,1,4,13,7.931644,1,...,36.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2374,2.814120e+07,9684809.0,1,80000000.0,94.0,0,4,11,7.956477,0,...,47.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2379,1.140952e+07,7118985.0,1,31000000.0,98.0,0,4,4,7.620215,0,...,59.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2380,1.815154e+07,7320066.0,1,22000000.0,95.0,0,4,6,7.940228,0,...,52.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2383,2.100383e+07,7857076.0,1,30000000.0,69.0,0,4,10,7.785305,0,...,74.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2385,1.576067e+06,84797.0,1,2000000.0,100.0,0,4,8,4.948760,0,...,90.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2386,1.952119e+07,7297694.0,1,60000000.0,118.0,1,4,10,7.994632,1,...,31.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2389,1.519070e+07,13528946.0,1,19000000.0,95.0,0,4,6,7.921536,0,...,29.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2391,3.510691e+07,31479235.0,1,150000000.0,103.0,1,4,9,8.078068,1,...,43.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2392,2.460902e+07,18361578.0,1,100000000.0,180.0,1,2,9,7.846590,1,...,75.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2398,3.678510e+07,35519007.0,1,135000000.0,128.0,0,4,4,8.059276,0,...,59.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2399,6.470942e+06,8811790.0,1,20000000.0,109.0,0,4,18,7.347944,0,...,81.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2402,4.926372e+07,66411834.0,1,190000000.0,116.0,0,4,14,8.190632,0,...,63.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2403,-4.503106e+06,2313149.0,1,6000000.0,109.0,0,4,16,6.654153,0,...,81.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2404,2.522936e+06,5161498.0,1,12600000.0,84.0,0,4,4,7.387090,0,...,32.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2410,2.982081e+07,18262471.0,1,70000000.0,104.0,0,4,9,8.141481,0,...,46.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2411,2.478945e+07,16411322.0,1,80000000.0,80.0,0,4,8,8.164795,0,...,35.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2412,2.487634e+06,8407513.0,1,20000000.0,105.0,0,4,15,7.843064,0,...,28.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2413,3.619844e+07,38531374.0,1,90000000.0,113.0,0,4,8,8.150756,0,...,54.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2416,2.715247e+07,21525560.0,1,54000000.0,108.0,0,4,5,8.051022,0,...,46.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2417,-1.347996e+06,3403159.0,1,12000000.0,94.0,0,4,6,6.894670,0,...,71.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2418,-9.409271e+06,260591.0,1,35000000.0,105.0,0,4,7,6.165418,0,...,64.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2422,1.697629e+07,17461108.0,1,45000000.0,90.0,1,2,9,8.074026,1,...,38.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2425,2.022804e+07,18426749.0,1,65000000.0,119.0,0,4,2,7.988882,0,...,57.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2428,1.987653e+07,10065630.0,1,24000000.0,101.0,0,4,6,7.913887,0,...,56.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [116]:
X = sm.add_constant(test[['production_budget','runtime_minutes','holiday_weekend','competitors',
                           'widest_release_sq','holiday_weekend_sq','day_of_week','widest_release','metascore']].join(
                                            pd.get_dummies(test['season']).join(
                                            pd.get_dummies(test['rating_categories']))))
Y = test['opening_weekend_take']

In [117]:
test_pred = pd.DataFrame(linmodel.predict(X),index=test.index)

In [118]:
final = pd.concat([test_pred,Y,X],axis=1)

In [119]:
final['diff'] = final[0] - final['opening_weekend_take']

In [120]:
final

,0,opening_weekend_take,const,production_budget,runtime_minutes,holiday_weekend,competitors,widest_release_sq,holiday_weekend_sq,day_of_week,...,fall,spring,summer,winter,Not Rated,PG,PG-13,R,other,diff
17,8.289295e+07,36302612.0,1,42000000.0,109.0,0,12,8.054523,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.659034e+07
18,3.193916e+07,108865.0,1,5000000.0,135.0,0,6,6.204558,0,3,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,3.183030e+07
37,4.771308e+07,3739702.0,1,7500000.0,95.0,0,12,6.954639,0,4,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,4.397338e+07
57,6.973557e+07,24476632.0,1,12000000.0,101.0,0,13,8.023880,0,4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,4.525894e+07
69,3.081884e+07,33262.0,1,70000000.0,127.0,1,8,2.833213,1,4,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.078558e+07
72,7.838170e+07,37132505.0,1,85000000.0,124.0,0,2,8.000014,0,4,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,4.124919e+07
79,6.850970e+07,13687087.0,1,155000000.0,175.0,1,7,7.801800,1,2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5.482261e+07
83,6.016915e+07,19449867.0,1,50000000.0,114.0,1,2,7.708411,1,4,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.071928e+07
86,6.942278e+07,8008423.0,1,45000000.0,86.0,0,7,8.041735,0,4,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,6.141435e+07
113,4.794488e+07,4961015.0,1,7000000.0,102.0,0,3,7.124478,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.298386e+07
119,4.373424e+07,1512224.0,1,20000000.0,125.0,0,14,6.706862,0,4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,4.222202e+07
125,4.168089e+07,763234.0,1,7500000.0,100.0,0,9,6.637258,0,4,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,4.091766e+07
127,9.440476e+07,46204168.0,1,150000000.0,138.0,0,6,8.168203,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.820059e+07
147,6.579725e+07,15005604.0,1,40000000.0,139.0,0,6,7.809947,0,4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,5.079164e+07
156,5.869903e+07,18575214.0,1,32000000.0,95.0,0,8,7.940940,0,4,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,4.012382e+07
171,6.036518e+07,2371803.0,1,15000000.0,100.0,0,11,7.470794,0,4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,5.799338e+07
173,4.974128e+07,12606928.0,1,50000000.0,139.0,1,3,7.515889,1,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,3.713435e+07
181,5.648996e+07,6176280.0,1,40000000.0,91.0,0,12,7.546974,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5.031368e+07
209,7.232937e+07,11007367.0,1,70000000.0,116.0,0,2,7.987524,0,4,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,6.132201e+07
224,6.339995e+07,7783266.0,1,45000000.0,99.0,0,9,7.883823,0,4,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.561668e+07
239,3.436855e+07,107577.0,1,21000000.0,91.0,0,11,5.123964,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.426098e+07
241,7.811535e+07,23450212.0,1,53000000.0,118.0,0,8,8.075894,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5.466514e+07
266,4.559378e+07,6383203.0,1,10000000.0,124.0,1,16,7.168580,1,4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.921058e+07
296,3.407863e+07,215681.0,1,5000000.0,110.0,0,5,6.234411,0,4,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.386295e+07
298,3.354016e+07,1705577.0,1,20000000.0,100.0,0,9,6.309918,0,4,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.183459e+07
320,7.660746e+07,14284031.0,1,40000000.0,117.0,1,13,8.176110,1,4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.232343e+07
336,9.107386e+07,26223128.0,1,150000000.0,96.0,0,5,8.203578,0,4,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,6.485073e+07
348,7.402797e+07,20686423.0,1,40000000.0,110.0,0,12,8.044947,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5.334155e+07
355,4.668355e+07,1992448.0,1,4000000.0,165.0,0,14,6.652863,0,4,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,4.469110e+07
371,7.164565e+07,9516855.0,1,28000000.0,90.0,0,19,7.881182,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.212880e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2099,4.703740e+07,3446375.0,1,27000000.0,99.0,0,6,7.313887,0,4,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,4.359103e+07
2108,2.996333e+07,172194.0,1,20000000.0,124.0,0,9,4.779123,0,4,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.979114e+07
2127,9.066263e+07,34221968.0,1,130000000.0,88.0,0,1,8.049108,0,2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.644066e+07
2128,5.981101e+07,12029832.0,1,25000000.0,97.0,1,5,8.006701,1,2,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.778118e+07
2131,7.326531e+07,17057213.0,1,75000000.0,121.0,0,6,7.997327,0,4,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,5.620810e+07
2140,9.569050e+07,42558390.0,1,200000000.0,115.0,1,6,8.189245,1,3,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.313211e+07
2163,6.087113e+07,33636303.0,1,12000000.0,122.0,0,15,7.626570,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.723483e+07
2165,3.117178e+07,116260.0,1,2000000.0,100.0,0,6,5.493061,0,2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.105552e+07
2166,5.670461e+07,9768899.0,1,80000000.0,145.0,1,3,7.617760,1,4,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,4.693571e+07
2183,7.154065e+07,14010409.0,1,48000000.0,101.0,0,12,8.115222,0,4,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,5.753024e+07
2189,9.223670e+07,25577758.0,1,125000000.0,118.0,0,10,8.188967,0,4,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,6.665894e+07
2206,5.664775e+07,3210765.0,1,30000000.0,106.0,0,4,7.708411,0,4,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.343698e+07
2229,7.977405e+07,41059405.0,1,92000000.0,113.0,0,2,7.940228,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.871464e+07
2243,7.465386e+07,30621445.0,1,65000000.0,137.0,1,8,8.101981,1,3,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,4.403241e+07
2249,6.281099e+07,21753759.0,1,22000000.0,121.0,0,7,7.982075,0,4,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4.105723e+07
2265,6.149023e+07,11277367.0,1,20000000.0,92.0,0,7,7.822044,0,4,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,5.021287e+07
2272,6.995376e+07,21027007.0,1,75000000.0,115.0,1,12,7.950855,1,3,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,4.892675e+07
2289,8.714267e+07,50746142.0,1,60000000.0,108.0,0,9,8.224967,0,4,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,3.639652e+07
2305,6.585126e+07,7091938.0,1,80000000.0,87.0,1,6,8.084254,1,4,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,5.875932e+07
2309,1.149114e+08,63087526.0,1,180000000.0,98.0,0,9,8.292048,0,4,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.182389e+07
2320,9.273954e+07,55214334.0,1,130000000.0,162.0,0,2,8.191740,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.752521e+07
2332,7.301568e+07,33900720.0,1,40000000.0,119.0,0,5,8.049108,0,4,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,3.911496e+07
2343,3.821089e+07,137418.0,1,3500000.0,101.0,0,6,6.320768,0,4,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,3.807347e+07
2358,8.995222e+07,32695407.0,1,100000000.0,101.0,0,12,8.225503,0,4,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,5.725682e+07
2371,6.683308e+07,6685381.0,1,40000000.0,98.0,0,10,7.883823,0,4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.014770e+07
2409,7.471723e+07,19610304.0,1,60000000.0,97.0,0,9,8.014336,0,4,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,5.510693e+07
2414,5.058421e+07,16123105.0,1,8000000.0,95.0,0,8,7.571988,0,4,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,3.446110e+07
2423,5.540991e+07,6888334.0,1,18000000.0,90.0,0,9,7.535297,0,4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,4.852158e+07
2431,7.909426e+07,24733155.0,1,23600000.0,88.0,0,12,8.061802,0,4,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.436110e+07
2432,7.856960e+07,20065617.0,1,80000000.0,104.0,0,13,8.155362,0,4,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,5.850399e+07